services:
  postgres:
    container_name: postgres_container
    image: postgres
    command: postgres -c 'max_connections=250'
    environment:
      # PG_DB: toko_buku_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      TZ: "Asia/Jakarta"
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgresn
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@test.mail"
      PGADMIN_DEFAULT_PASSWORD: "root"
      # PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgresn
    restart: always

networks:
  postgresn:
    driver: bridge

volumes:
    postgres:
    pgadmin: